### ISSUE TITLE
Kubernetes 1.24 doesn't automatically generate token anymore.

### ISSUE THREAD

**Issue by itdove** [stolostron/cm-cli#233]
https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0

when I create the sa, I will need also to create a token with
```
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cicd
  annotations:
    kubernetes.io/service-account.name: "cicd"
    ```
